Regression 


Only One hot encoding 


PCA


RandomizedSearchCv (=GridSearchCV)

In [161]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeRegressor
#from sklearn.linear_model import LinearRegression, SGDRegressor !!!

from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score
import numpy as np

from sklearn.datasets import make_regression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.feature_selection import VarianceThreshold, SelectKBest, f_regression, RFECV, SelectFromModel

from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.decomposition import PCA

In [162]:
url = "https://drive.google.com/file/d/1idsy5wqE1fhiRY7dAiKgq-eKyTzoeW01/view?usp=sharing"
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
data = df = pd.read_csv(path)
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
#data.drop(columns=['Id'])   #this column has nothing important

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [163]:
#Create X and y labels 
X = data                 #drop if need a few columns are't usefull
y = X.pop("SalePrice")

In [164]:
#Split data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [165]:
#Preprocessing
X_cat = X.select_dtypes(exclude="number").copy()  #.columns.copy()
X_num = X.select_dtypes(include="number").copy()   #.columns.copy()


numeric_pipe = make_pipeline(
    SimpleImputer(strategy="mean"),
    MinMaxScaler())

categoric_pipe = make_pipeline(
    SimpleImputer(strategy="constant", fill_value="N_A"),
    OneHotEncoder(handle_unknown='ignore', sparse_output=False)
)



full_preprocessing = ColumnTransformer(
    transformers=[
        ("num_pipe", numeric_pipe, X_num.columns),
        ("cat_pipe", categoric_pipe, X_cat.columns)
    ]
)

In [166]:
from sklearn.model_selection import GridSearchCV
big_pipeline = make_pipeline(preprocessor,
                             PCA(),
                              DecisionTreeRegressor())

param_grid = {
    "columntransformer__num_pipe__simpleimputer__strategy":["mean", "median"],
    "decisiontreeregressor__max_depth": range(2, 14, 2),
}
  
search_dt = GridSearchCV(big_pipeline,
                      param_grid,
                      cv=5,
                      verbose=1)

search_dt.fit(X_train, y_train)  

scores = {"dtree" : search_dt.best_score_}
scores

Fitting 5 folds for each of 12 candidates, totalling 60 fits

{'dtree': 0.5384403245372764}

In [168]:
search_dt.best_params_

{'columntransformer__num_pipe__simpleimputer__strategy': 'mean',
 'decisiontreeregressor__max_depth': 2}

In [216]:
dt_1 = search_dt.predict(X_test)

In [217]:
dt_1_r2 = r2_score(y_true = y_test,
                  y_pred = dt_1)

In [218]:
comparing_models_df.loc['dt_1_r2']=dt_1_r2

comparing_models_df

                R2
pca_r2    0.640000
pca_2_r2  0.753030
dt_1_r2   0.569284

In [ ]:
REGRESSORS (exact price)!!!

In [220]:
from sklearn.model_selection import GridSearchCV

dt_pipeline = make_pipeline(full_preprocessing,
                            PCA(),
                            DecisionTreeRegressor())

param_grid = {
    "columntransformer__num_pipe__simpleimputer__strategy":["mean"],#, "median"],
    "pca__n_components": list(range(10, 40, 5)),#10, 310, 20)),
    "decisiontreeregressor__max_depth": range(8, 10, 2),
    "decisiontreeregressor__min_samples_leaf": range(3, 11, 2)
}

search_dtr_2 = GridSearchCV(dt_pipeline,
                      param_grid,
                      cv=5,
                      verbose=1)

search_dtr_2.fit(X_train, y_train)

scores = {"DecisionTreeRegressor" : search_dtr_2.best_score_}
scores

Fitting 5 folds for each of 24 candidates, totalling 120 fits

{'DecisionTreeRegressor': 0.6037161975044626}

In [222]:
dt_2 = search_dtr_2.predict(X_test)

In [223]:
dt_2_r2 = r2_score(y_true = y_test,
                  y_pred = dt_2)

In [224]:
comparing_models_df.loc['dt_2_r2']=pca_2_r2

comparing_models_df

                R2
pca_r2    0.640000
pca_2_r2  0.753030
dt_1_r2   0.569284
dt_2_r2   0.753030

In [179]:
from sklearn.model_selection import GridSearchCV

dt_pipeline = make_pipeline(full_preprocessing,
                            PCA(),
                            KNeighborsRegressor())

param_grid = {
    "columntransformer__num_pipe__simpleimputer__strategy":["mean"],#, "median"],
    "pca__n_components": list(range(10, 80, 5)),#10, 310, 20)),
    'kneighborsregressor__n_neighbors':[9,15,2],
    'kneighborsregressor__weights': ["uniform", "distance"],
    'kneighborsregressor__algorithm' : ["auto", "ball_tree", "kd_tree"]
}

search_dtr = GridSearchCV(dt_pipeline,
                      param_grid,
                      cv=5,
                      verbose=1)

search_dtr.fit(X_train, y_train)

scores = {"KNeighborsRegressor" : search_dtr.best_score_}
scores

Fitting 5 folds for each of 252 candidates, totalling 1260 fits

{'KNeighborsRegressor': 0.7305369076976405}

In [180]:
search_dtr.best_params_

{'columntransformer__num_pipe__simpleimputer__strategy': 'mean',
 'kneighborsregressor__algorithm': 'ball_tree',
 'kneighborsregressor__n_neighbors': 9,
 'kneighborsregressor__weights': 'distance',
 'pca__n_components': 65}

In [181]:
model_pipeline = make_pipeline(full_preprocessing,
                               StandardScaler(),
                               PCA(n_components=65),
                               KNeighborsClassifier(algorithm='ball_tree',
                                                    weights='distance',
                                                    p=2,
                                                    n_neighbors=9))

model_pipeline.fit(X_train, y_train)


best_score_retrain_pca = model_pipeline.score(X_train, y_train)

print(f"{round(best_score_retrain_pca * 100, 2)}% accuracy")

100.0% accuracy

In [185]:
pca_pred = model_pipeline.predict(X_test)

In [186]:
pca_r2 = r2_score(y_true = y_test,
                  y_pred = pca_pred)

In [188]:
comparing_models_df = pd.DataFrame({"R2": [pca_r2]}, #, dt_r2, sgd_r2, lr_r2]},
                                    index=["pca_r2"])  #, "decision_tree", "sgd", "linear_regression"])

comparing_models_df

          R2
pca_r2  0.64

In [211]:
start_time = time.time()

model_pipeline1 = make_pipeline(full_preprocessing,
                               StandardScaler(),
                               PCA(n_components=40),
                               KNeighborsClassifier(algorithm='ball_tree',
                                                    weights='distance',
                                                    p=2,
                                                    n_neighbors=4))

model_pipeline1.fit(X_train, y_train)

end_time = time.time()

time_taken_retrain_pca = end_time - start_time
best_score_retrain_pca = model_pipeline1.score(X_train, y_train)

print("--- %s seconds ---" % (time_taken_retrain_pca))
print(f"{round(best_score_retrain_pca * 100, 2)}% accuracy")

--- 0.10057497024536133 seconds ---
99.91% accuracy

In [212]:
pca_2 = model_pipeline1.predict(X_test)

In [236]:
ggg = pd.concat([y, pca_2_test], axis = 1)
ggg

        Id       0
0     1461  112500
1     1462  151500
2     1463  193000
3     1464  193000
4     1465  180000
...    ...     ...
1454  2915   97000
1455  2916   83500
1456  2917  149900
1457  2918  112000
1458  2919  188000

[1459 rows x 2 columns]

In [242]:
ggg.rename(columns = {0:'SalePrice'}, inplace=True)
ggg.head()

     Id  SalePrice
0  1461     112500
1  1462     151500
2  1463     193000
3  1464     193000
4  1465     180000

In [243]:
#pca_2_test = pd.DataFrame(model_pipeline1.predict(test_data))
ggg.to_csv('PCA_regression_gg.csv', index=False)

In [213]:
pca_2_r2 = r2_score(y_true = y_test,
                  y_pred = pca_2)

In [214]:
comparing_models_df.loc['pca_2_r2']=pca_2_r2

comparing_models_df

               R2
pca_r2    0.64000
pca_2_r2  0.75303

In [50]:
search_knn.best_params_

{'columntransformer__num_pipe__simpleimputer__strategy': 'median',
 'kneighborsregressor__n_neighbors': 9,
 'pca__n_components': 11}

In [225]:
url = "https://drive.google.com/file/d/1o4ivk9gp0YR9gPsAOj-Z7XRSaT_CkfmY/view?usp=sharing"
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
test_data = pd.read_csv(path)
test_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [233]:
y=test_data.pop('Id')